name: 'A Treat for your PR'
description: 'Posts a gif on every PR as a reward for pushing code.'
author: 'Parthiv Kativarapu'
branding:
  icon: 'code'  
  color: 'blue'
inputs:
  GITHUB_TOKEN:        #Github token      
    description: 'Github token for the repository.'
    required: true
runs:
  using: 'node12'
  main: 'lib/main.js'
